export type Country = {
  name: string
  code: string
}

export type ContinentGroup = {
  continent: string
  countries: Country[]
}

export const COUNTRIES_BY_CONTINENT: ContinentGroup[] = [
  {
    continent: 'Europe',
    countries: [
      { name: 'Albanie', code: 'AL' },
      { name: 'Allemagne', code: 'DE' },
      { name: 'Andorre', code: 'AD' },
      { name: 'Autriche', code: 'AT' },
      { name: 'Belgique', code: 'BE' },
      { name: 'Biélorussie', code: 'BY' },
      { name: 'Bosnie-Herzégovine', code: 'BA' },
      { name: 'Bulgarie', code: 'BG' },
      { name: 'Chypre', code: 'CY' },
      { name: 'Croatie', code: 'HR' },
      { name: 'Danemark', code: 'DK' },
      { name: 'Espagne', code: 'ES' },
      { name: 'Estonie', code: 'EE' },
      { name: 'Finlande', code: 'FI' },
      { name: 'France', code: 'FR' },
      { name: 'Grèce', code: 'GR' },
      { name: 'Hongrie', code: 'HU' },
      { name: 'Irlande', code: 'IE' },
      { name: 'Islande', code: 'IS' },
      { name: 'Italie', code: 'IT' },
      { name: 'Kosovo', code: 'XK' },
      { name: 'Lettonie', code: 'LV' },
      { name: 'Liechtenstein', code: 'LI' },
      { name: 'Lituanie', code: 'LT' },
      { name: 'Luxembourg', code: 'LU' },
      { name: 'Macédoine du Nord', code: 'MK' },
      { name: 'Malte', code: 'MT' },
      { name: 'Moldavie', code: 'MD' },
      { name: 'Monaco', code: 'MC' },
      { name: 'Monténégro', code: 'ME' },
      { name: 'Norvège', code: 'NO' },
      { name: 'Pays-Bas', code: 'NL' },
      { name: 'Pologne', code: 'PL' },
      { name: 'Portugal', code: 'PT' },
      { name: 'Roumanie', code: 'RO' },
      { name: 'Royaume-Uni', code: 'GB' },
      { name: 'Russie', code: 'RU' },
      { name: 'Saint-Marin', code: 'SM' },
      { name: 'Serbie', code: 'RS' },
      { name: 'Slovaquie', code: 'SK' },
      { name: 'Slovénie', code: 'SI' },
      { name: 'Suède', code: 'SE' },
      { name: 'Suisse', code: 'CH' },
      { name: 'Tchéquie', code: 'CZ' },
      { name: 'Ukraine', code: 'UA' },
      { name: 'Vatican', code: 'VA' },
    ],
  },
  {
    continent: 'Afrique',
    countries: [
      { name: 'Afrique du Sud', code: 'ZA' },
      { name: 'Algérie', code: 'DZ' },
      { name: 'Angola', code: 'AO' },
      { name: 'Bénin', code: 'BJ' },
      { name: 'Botswana', code: 'BW' },
      { name: 'Burkina Faso', code: 'BF' },
      { name: 'Burundi', code: 'BI' },
      { name: 'Cameroun', code: 'CM' },
      { name: 'Cap-Vert', code: 'CV' },
      { name: 'Comores', code: 'KM' },
      { name: 'Congo (Brazzaville)', code: 'CG' },
      { name: 'Congo (RDC)', code: 'CD' },
      { name: 'Côte d\'Ivoire', code: 'CI' },
      { name: 'Djibouti', code: 'DJ' },
      { name: 'Égypte', code: 'EG' },
      { name: 'Érythrée', code: 'ER' },
      { name: 'Eswatini', code: 'SZ' },
      { name: 'Éthiopie', code: 'ET' },
      { name: 'Gabon', code: 'GA' },
      { name: 'Gambie', code: 'GM' },
      { name: 'Ghana', code: 'GH' },
      { name: 'Guinée', code: 'GN' },
      { name: 'Guinée équatoriale', code: 'GQ' },
      { name: 'Guinée-Bissau', code: 'GW' },
      { name: 'Kenya', code: 'KE' },
      { name: 'Lesotho', code: 'LS' },
      { name: 'Libéria', code: 'LR' },
      { name: 'Libye', code: 'LY' },
      { name: 'Madagascar', code: 'MG' },
      { name: 'Malawi', code: 'MW' },
      { name: 'Mali', code: 'ML' },
      { name: 'Maroc', code: 'MA' },
      { name: 'Maurice', code: 'MU' },
      { name: 'Mauritanie', code: 'MR' },
      { name: 'Mozambique', code: 'MZ' },
      { name: 'Namibie', code: 'NA' },
      { name: 'Niger', code: 'NE' },
      { name: 'Nigéria', code: 'NG' },
      { name: 'Ouganda', code: 'UG' },
      { name: 'Rwanda', code: 'RW' },
      { name: 'Sao Tomé-et-Príncipe', code: 'ST' },
      { name: 'Sénégal', code: 'SN' },
      { name: 'Seychelles', code: 'SC' },
      { name: 'Sierra Leone', code: 'SL' },
      { name: 'Somalie', code: 'SO' },
      { name: 'Soudan', code: 'SD' },
      { name: 'Soudan du Sud', code: 'SS' },
      { name: 'Tanzanie', code: 'TZ' },
      { name: 'Tchad', code: 'TD' },
      { name: 'Togo', code: 'TG' },
      { name: 'Tunisie', code: 'TN' },
      { name: 'Zambie', code: 'ZM' },
      { name: 'Zimbabwe', code: 'ZW' },
    ],
  },
  {
    continent: 'Amériques',
    countries: [
      { name: 'Antigua-et-Barbuda', code: 'AG' },
      { name: 'Argentine', code: 'AR' },
      { name: 'Bahamas', code: 'BS' },
      { name: 'Barbade', code: 'BB' },
      { name: 'Belize', code: 'BZ' },
      { name: 'Bolivie', code: 'BO' },
      { name: 'Brésil', code: 'BR' },
      { name: 'Canada', code: 'CA' },
      { name: 'Chili', code: 'CL' },
      { name: 'Colombie', code: 'CO' },
      { name: 'Costa Rica', code: 'CR' },
      { name: 'Cuba', code: 'CU' },
      { name: 'Dominique', code: 'DM' },
      { name: 'Équateur', code: 'EC' },
      { name: 'El Salvador', code: 'SV' },
      { name: 'États-Unis', code: 'US' },
      { name: 'Grenade', code: 'GD' },
      { name: 'Guatemala', code: 'GT' },
      { name: 'Guyana', code: 'GY' },
      { name: 'Haïti', code: 'HT' },
      { name: 'Honduras', code: 'HN' },
      { name: 'Jamaïque', code: 'JM' },
      { name: 'Mexique', code: 'MX' },
      { name: 'Nicaragua', code: 'NI' },
      { name: 'Panama', code: 'PA' },
      { name: 'Paraguay', code: 'PY' },
      { name: 'Pérou', code: 'PE' },
      { name: 'République dominicaine', code: 'DO' },
      { name: 'Saint-Christophe-et-Niévès', code: 'KN' },
      { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC' },
      { name: 'Sainte-Lucie', code: 'LC' },
      { name: 'Suriname', code: 'SR' },
      { name: 'Trinité-et-Tobago', code: 'TT' },
      { name: 'Uruguay', code: 'UY' },
      { name: 'Vénézuéla', code: 'VE' },
    ],
  },
  {
    continent: 'Asie',
    countries: [
      { name: 'Afghanistan', code: 'AF' },
      { name: 'Arabie saoudite', code: 'SA' },
      { name: 'Arménie', code: 'AM' },
      { name: 'Azerbaïdjan', code: 'AZ' },
      { name: 'Bahreïn', code: 'BH' },
      { name: 'Bangladesh', code: 'BD' },
      { name: 'Bhoutan', code: 'BT' },
      { name: 'Birmanie (Myanmar)', code: 'MM' },
      { name: 'Brunei', code: 'BN' },
      { name: 'Cambodge', code: 'KH' },
      { name: 'Chine', code: 'CN' },
      { name: 'Corée du Nord', code: 'KP' },
      { name: 'Corée du Sud', code: 'KR' },
      { name: 'Émirats arabes unis', code: 'AE' },
      { name: 'Géorgie', code: 'GE' },
      { name: 'Inde', code: 'IN' },
      { name: 'Indonésie', code: 'ID' },
      { name: 'Irak', code: 'IQ' },
      { name: 'Iran', code: 'IR' },
      { name: 'Israël', code: 'IL' },
      { name: 'Japon', code: 'JP' },
      { name: 'Jordanie', code: 'JO' },
      { name: 'Kazakhstan', code: 'KZ' },
      { name: 'Kirghizistan', code: 'KG' },
      { name: 'Koweït', code: 'KW' },
      { name: 'Laos', code: 'LA' },
      { name: 'Liban', code: 'LB' },
      { name: 'Malaisie', code: 'MY' },
      { name: 'Maldives', code: 'MV' },
      { name: 'Mongolie', code: 'MN' },
      { name: 'Népal', code: 'NP' },
      { name: 'Oman', code: 'OM' },
      { name: 'Ouzbékistan', code: 'UZ' },
      { name: 'Pakistan', code: 'PK' },
      { name: 'Palestine', code: 'PS' },
      { name: 'Philippines', code: 'PH' },
      { name: 'Qatar', code: 'QA' },
      { name: 'Singapour', code: 'SG' },
      { name: 'Sri Lanka', code: 'LK' },
      { name: 'Syrie', code: 'SY' },
      { name: 'Tadjikistan', code: 'TJ' },
      { name: 'Taïwan', code: 'TW' },
      { name: 'Thaïlande', code: 'TH' },
      { name: 'Timor oriental', code: 'TL' },
      { name: 'Turkménistan', code: 'TM' },
      { name: 'Turquie', code: 'TR' },
      { name: 'Vietnam', code: 'VN' },
      { name: 'Yémen', code: 'YE' },
    ],
  },
  {
    continent: 'Océanie',
    countries: [
      { name: 'Australie', code: 'AU' },
      { name: 'Fidji', code: 'FJ' },
      { name: 'Îles Marshall', code: 'MH' },
      { name: 'Îles Salomon', code: 'SB' },
      { name: 'Kiribati', code: 'KI' },
      { name: 'Micronésie', code: 'FM' },
      { name: 'Nauru', code: 'NR' },
      { name: 'Nouvelle-Zélande', code: 'NZ' },
      { name: 'Palaos', code: 'PW' },
      { name: 'Papouasie-Nouvelle-Guinée', code: 'PG' },
      { name: 'Samoa', code: 'WS' },
      { name: 'Tonga', code: 'TO' },
      { name: 'Tuvalu', code: 'TV' },
      { name: 'Vanuatu', code: 'VU' },
    ],
  },
]

/** Flat list for easy lookup by code */
export const ALL_COUNTRIES: Country[] = COUNTRIES_BY_CONTINENT.flatMap((g) => g.countries)

export function getCountryByCode(code: string): Country | undefined {
  return ALL_COUNTRIES.find((c) => c.code === code)
}
